In [3]:
import numpy as np

In [4]:
array1 = np.array([1,2,3])
print('array1 type:',type(array1))
print('array1 array 형태:', array1.shape)

array2 = np.array([[1,2,3],
                 [2,3,4]])
print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape)

array3 = np.array([[1,2,3]])
print('array3 type:', type(array3))
print('array3 array 형태:', array3.shape)

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [9]:
print('array1: {}차원, array2: {}차원, array3: {}차원'.format(array1.ndim, array2.ndim, array3.ndim))

array1: 1차원, array2: 2차원, array3: 2차원


In [5]:
list1 = [1,2,3]
print(type(list1))
array1 = np.array(list)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
<class 'list'> object


In [6]:
list2 = [1,2,'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1,2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U11
[1. 2. 3.] float64


In [8]:
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


In [11]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


In [12]:
zero_array = np.zeros((3,2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)


In [14]:
one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


In [19]:
array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2,5)
print('array2:\n', array2)

array3 = array1.reshape(5,2)
print('array3:\n', array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [20]:
array1 = np.arange(10)
print(array1)
array2 = array1.reshape(-1,5)
print(array2)
array3 = array1.reshape(5,-1)
print(array3)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [24]:
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print(array3d)

# 3차원 ndarray를 2차원 ndarray로 변환
array5= array3d.reshape(-1,1)
print(array5)
print(array5.shape)

# 1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1,1)
print(array6)
print(array6.shape)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]
(8, 1)
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]
(8, 1)


In [27]:
array1 = np.arange(start=1, stop=10)
print(array1)

value = array1[2]
print(value)
print(type(value))

[1 2 3 4 5 6 7 8 9]
3
<class 'numpy.int32'>


In [29]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)

print(array2d[0,0])
print(array2d[0,1])
print(array2d[1,0])
print(array2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
2
4
9


In [30]:
array1 = np.arange(start=1, stop=10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [33]:
array1d = np.arange(1,10)
array2d = array1d.reshape(3,3)
print(array2d)
print(array2d[0:2,0:2])
print(array2d[1:3,0:3])
print(array2d[1:3,:])
print(array2d[:,:])
print(array2d[:2,1:])
print(array2d[:2,0])

print(array2d[0])
print(array2d[1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]]
[[4 5 6]
 [7 8 9]]
[[4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 3]
 [5 6]]
[1 4]
[1 2 3]
[4 5 6]


In [38]:
array1d = np.arange(1,10)
array2d = array1d.reshape(3,3)
print(array2d)

array3 = array2d[[0,1], 2]
print(array3)
print(array3.tolist())

array4 = array2d[[0,1], 0:2]
print(array4)
print(array4.tolist())

array5 = array2d[[0,1]]
print(array5)
print(array5.tolist())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[3 6]
[3, 6]
[[1 2]
 [4 5]]
[[1, 2], [4, 5]]
[[1 2 3]
 [4 5 6]]
[[1, 2, 3], [4, 5, 6]]


In [42]:
array1d = np.arange(1,10)
array2d = array1d.reshape(-1,3)
print(array2d)

array3 = array1d[array1d>5]
print(array3)

print(array1d>5)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[6 7 8 9]
[False False False False False  True  True  True  True]


In [45]:
boolean_indexes = np.array([False, False, False,False,False,True,True,True,True])
array3 = array1d[boolean_indexes]
print(array3)

[6 7 8 9]


In [47]:
indexes = np.array([5,6,7,8])
array4 = array1d[indexes]
print(array4)

[6 7 8 9]


In [48]:
org_array = np.array([3,1,9,5])
print(org_array)

sort_array1 = np.sort(org_array)
print(sort_array1)

[3 1 9 5]
[1 3 5 9]


In [51]:
sort_array2 = org_array.sort()
print(sort_array2)
print(org_array)

None
[1 3 5 9]


In [53]:
sort_array1_desc = np.sort(org_array)[::-1]
print(sort_array1_desc)

[9 5 3 1]


In [55]:
array2d = np.array([[8,12],
                   [7,1]])

sort_array2d_axis0 = np.sort(array2d, axis=0)
print(sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print(sort_array2d_axis1)

[[ 7  1]
 [ 8 12]]
[[ 8 12]
 [ 1  7]]


In [56]:
org_array = np.array([3,1,9,5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print(sort_indices)

<class 'numpy.ndarray'>
[1 0 3 2]


In [57]:
org_array = np.array([3,1,9,5])
sort_indices_desc = np.argsort(org_array)[::-1]
print(sort_indices_desc)

[2 3 0 1]


In [58]:
name_array = np.array(['John', 'Mike','Sarah','Kate','Samuel'])
score_array = np.array([78, 95, 84, 98, 88])

sort_indices_asc = np.argsort(score_array)
print(sort_indices_asc)
print(name_array[sort_indices_asc])

[0 2 4 1 3]
['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


In [59]:
A = np.array([[1,2,3],
             [4,5,6]])

B = np.array([[7,8],
             [9,10],
              [11,12]])

dot_product = np.dot(A,B)
print(dot_product)

[[ 58  64]
 [139 154]]


In [60]:
A = np.array([[1,2],
             [3,4]])
transpose_mat = np.transpose(A)
print(transpose_mat)

[[1 3]
 [2 4]]


Everything up-to-date
